import type { Metadata } from "next";
import { Manrope, Geist_Mono } from "next/font/google";
import { SoundProvider } from "@web-kits/audio/react";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
return (
    <SoundProvider enabled={true} volume={1}>
      <html lang="en" suppressHydrationWarning className={`${manrope.variable} ${geistMono.variable} h-full antialiased`} >
        <body className="min-h-full flex flex-col">{children}</body>
      </html>
    </SoundProvider>
  );
}
